### ISSUE TITLE
Add option to export to TCX

### ISSUE THREAD

**Issue by rldukes** [nachmore/unBand#39]
Love the app. very useful thank you.
I am trying to export my data to gpx but it is only giving me the option to export to csv. Is there a way to change this and do you know when it will be possible to export the steps too in to gpx.
Thank you! Great app!
Rob

**Comment by nachmore** [comment]
When you select a Run you should see an "export to GPX" button.

Unfortunately there is not enough data in the steps data to be able to export to GPX, since the GPS is not active throughout the day. Step data export is checked in, I'm hoping to wrap up some loose ends and release the next version next week.

**Comment by rldukes** [comment]
Thanks for the quick reply.
Think because it didn't seem to capture my gps location, only distance its not displaying the option. I run sometimes on the treadmill and measures my distance, and heart rate but gps is not used. Is there someway to export as tcx, would that not require the gps location? Thank you!
Rob

**Comment by ProH4Ck** [comment]
Good idea. I'm the developer who wrote gpx export code. In the next few days I'll implement also tcx export.

**Comment by rldukes** [comment]
Cool. Thank you so much. Can't wait to give it a try!

**Comment by ProH4Ck** [comment]
I've implemented TCX export. Waiting for @nachmore to approve my pull request.

**Comment by rldukes** [comment]
Excellent, can't wait to give it a try when it is released! Thank you :)

**Comment by rldukes** [comment]
Hi,Sorry to bother you but not sure if I am doing something wrong but when I try to export I still don't seem to get the option for tcx sorry. I can see all my runs, daily activities, bike etc. but not option to export as tcx.

**Comment by nachmore** [comment]
This was checked in with 12b12088fc66ac8ec947737c518ebde3ce9cb28e but not released yet (delayed due to the large changes required to get unBand working with the new Desktop app), stay tuned...

**Comment by rldukes** [comment]
Sure, will do. 
Thank you!
